// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pkg/protocol/protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UdpPort       uint32                 `protobuf:"varint,1,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloMessage) Reset() {
	*x = HelloMessage{}
	mi := &file_pkg_protocol_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloMessage) ProtoMessage() {}

func (x *HelloMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloMessage.ProtoReflect.Descriptor instead.
func (*HelloMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *HelloMessage) GetUdpPort() uint32 {
	if x != nil {
		return x.UdpPort
	}
	return 0
}

type SetStationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationNumber uint32                 `protobuf:"varint,1,opt,name=station_number,json=stationNumber,proto3" json:"station_number,omitempty"`
	UdpPort       uint32                 `protobuf:"varint,2,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStationMessage) Reset() {
	*x = SetStationMessage{}
	mi := &file_pkg_protocol_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStationMessage) ProtoMessage() {}

func (x *SetStationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStationMessage.ProtoReflect.Descriptor instead.
func (*SetStationMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *SetStationMessage) GetStationNumber() uint32 {
	if x != nil {
		return x.StationNumber
	}
	return 0
}

func (x *SetStationMessage) GetUdpPort() uint32 {
	if x != nil {
		return x.UdpPort
	}
	return 0
}

type WelcomeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumStations   uint32                 `protobuf:"varint,1,opt,name=num_stations,json=numStations,proto3" json:"num_stations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeMessage) Reset() {
	*x = WelcomeMessage{}
	mi := &file_pkg_protocol_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeMessage) ProtoMessage() {}

func (x *WelcomeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeMessage.ProtoReflect.Descriptor instead.
func (*WelcomeMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *WelcomeMessage) GetNumStations() uint32 {
	if x != nil {
		return x.NumStations
	}
	return 0
}

type AnnounceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SongName      string                 `protobuf:"bytes,1,opt,name=song_name,json=songName,proto3" json:"song_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceMessage) Reset() {
	*x = AnnounceMessage{}
	mi := &file_pkg_protocol_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceMessage) ProtoMessage() {}

func (x *AnnounceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceMessage.ProtoReflect.Descriptor instead.
func (*AnnounceMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *AnnounceMessage) GetSongName() string {
	if x != nil {
		return x.SongName
	}
	return ""
}

type InvalidCommandMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyString   string                 `protobuf:"bytes,1,opt,name=reply_string,json=replyString,proto3" json:"reply_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidCommandMessage) Reset() {
	*x = InvalidCommandMessage{}
	mi := &file_pkg_protocol_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidCommandMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidCommandMessage) ProtoMessage() {}

func (x *InvalidCommandMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidCommandMessage.ProtoReflect.Descriptor instead.
func (*InvalidCommandMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *InvalidCommandMessage) GetReplyString() string {
	if x != nil {
		return x.ReplyString
	}
	return ""
}

type StationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationNumber uint32                 `protobuf:"varint,1,opt,name=station_number,json=stationNumber,proto3" json:"station_number,omitempty"`
	SongName      string                 `protobuf:"bytes,2,opt,name=song_name,json=songName,proto3" json:"song_name,omitempty"`
	BitrateLevels []string               `protobuf:"bytes,3,rep,name=bitrate_levels,json=bitrateLevels,proto3" json:"bitrate_levels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StationInfo) Reset() {
	*x = StationInfo{}
	mi := &file_pkg_protocol_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationInfo) ProtoMessage() {}

func (x *StationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationInfo.ProtoReflect.Descriptor instead.
func (*StationInfo) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *StationInfo) GetStationNumber() uint32 {
	if x != nil {
		return x.StationNumber
	}
	return 0
}

func (x *StationInfo) GetSongName() string {
	if x != nil {
		return x.SongName
	}
	return ""
}

func (x *StationInfo) GetBitrateLevels() []string {
	if x != nil {
		return x.BitrateLevels
	}
	return nil
}

type ListStationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStationsRequest) Reset() {
	*x = ListStationsRequest{}
	mi := &file_pkg_protocol_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStationsRequest) ProtoMessage() {}

func (x *ListStationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStationsRequest.ProtoReflect.Descriptor instead.
func (*ListStationsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protocol_proto_rawDescGZIP(), []int{6}
}

type ListStationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stations      []*StationInfo         `protobuf:"bytes,1,rep,name=stations,proto3" json:"stations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStationsResponse) Reset() {
	*x = ListStationsResponse{}
	mi := &file_pkg_protocol_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStationsResponse) ProtoMessage() {}

func (x *ListStationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStationsResponse.ProtoReflect.Descriptor instead.
func (*ListStationsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *ListStationsResponse) GetStations() []*StationInfo {
	if x != nil {
		return x.Stations
	}
	return nil
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UdpPort       uint32                 `protobuf:"varint,2,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_pkg_protocol_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *DisconnectRequest) GetUdpPort() uint32 {
	if x != nil {
		return x.UdpPort
	}
	return 0
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_pkg_protocol_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *DisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_Announce
	//	*ServerEvent_Invalid
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_pkg_protocol_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetAnnounce() *AnnounceMessage {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Announce); ok {
			return x.Announce
		}
	}
	return nil
}

func (x *ServerEvent) GetInvalid() *InvalidCommandMessage {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Invalid); ok {
			return x.Invalid
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_Announce struct {
	Announce *AnnounceMessage `protobuf:"bytes,1,opt,name=announce,proto3,oneof"`
}

type ServerEvent_Invalid struct {
	Invalid *InvalidCommandMessage `protobuf:"bytes,2,opt,name=invalid,proto3,oneof"`
}

func (*ServerEvent_Announce) isServerEvent_Event() {}

func (*ServerEvent_Invalid) isServerEvent_Event() {}

var File_pkg_protocol_protocol_proto protoreflect.FileDescriptor

const file_pkg_protocol_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/protocol/protocol.proto\x12\bprotocol\")\n" +
	"\fHelloMessage\x12\x19\n" +
	"\budp_port\x18\x01 \x01(\rR\audpPort\"U\n" +
	"\x11SetStationMessage\x12%\n" +
	"\x0estation_number\x18\x01 \x01(\rR\rstationNumber\x12\x19\n" +
	"\budp_port\x18\x02 \x01(\rR\audpPort\"3\n" +
	"\x0eWelcomeMessage\x12!\n" +
	"\fnum_stations\x18\x01 \x01(\rR\vnumStations\".\n" +
	"\x0fAnnounceMessage\x12\x1b\n" +
	"\tsong_name\x18\x01 \x01(\tR\bsongName\":\n" +
	"\x15InvalidCommandMessage\x12!\n" +
	"\freply_string\x18\x01 \x01(\tR\vreplyString\"x\n" +
	"\vStationInfo\x12%\n" +
	"\x0estation_number\x18\x01 \x01(\rR\rstationNumber\x12\x1b\n" +
	"\tsong_name\x18\x02 \x01(\tR\bsongName\x12%\n" +
	"\x0ebitrate_levels\x18\x03 \x03(\tR\rbitrateLevels\"\x15\n" +
	"\x13ListStationsRequest\"I\n" +
	"\x14ListStationsResponse\x121\n" +
	"\bstations\x18\x01 \x03(\v2\x15.protocol.StationInfoR\bstations\".\n" +
	"\x11DisconnectRequest\x12\x19\n" +
	"\budp_port\x18\x02 \x01(\rR\audpPort\".\n" +
	"\x12DisconnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8c\x01\n" +
	"\vServerEvent\x127\n" +
	"\bannounce\x18\x01 \x01(\v2\x19.protocol.AnnounceMessageH\x00R\bannounce\x12;\n" +
	"\ainvalid\x18\x02 \x01(\v2\x1f.protocol.InvalidCommandMessageH\x00R\ainvalidB\a\n" +
	"\x05event2\xac\x02\n" +
	"\x0fSnowcastControl\x12=\n" +
	"\tHandshake\x12\x16.protocol.HelloMessage\x1a\x18.protocol.WelcomeMessage\x12M\n" +
	"\fListStations\x12\x1d.protocol.ListStationsRequest\x1a\x1e.protocol.ListStationsResponse\x12B\n" +
	"\n" +
	"SetStation\x12\x1b.protocol.SetStationMessage\x1a\x15.protocol.ServerEvent0\x01\x12G\n" +
	"\n" +
	"Disconnect\x12\x1b.protocol.DisconnectRequest\x1a\x1c.protocol.DisconnectResponseB$Z\"snowcast-jamesyan2028/pkg/protocolb\x06proto3"

var (
	file_pkg_protocol_protocol_proto_rawDescOnce sync.Once
	file_pkg_protocol_protocol_proto_rawDescData []byte
)

func file_pkg_protocol_protocol_proto_rawDescGZIP() []byte {
	file_pkg_protocol_protocol_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_protocol_proto_rawDesc), len(file_pkg_protocol_protocol_proto_rawDesc)))
	})
	return file_pkg_protocol_protocol_proto_rawDescData
}

var file_pkg_protocol_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_protocol_protocol_proto_goTypes = []any{
	(*HelloMessage)(nil),          // 0: protocol.HelloMessage
	(*SetStationMessage)(nil),     // 1: protocol.SetStationMessage
	(*WelcomeMessage)(nil),        // 2: protocol.WelcomeMessage
	(*AnnounceMessage)(nil),       // 3: protocol.AnnounceMessage
	(*InvalidCommandMessage)(nil), // 4: protocol.InvalidCommandMessage
	(*StationInfo)(nil),           // 5: protocol.StationInfo
	(*ListStationsRequest)(nil),   // 6: protocol.ListStationsRequest
	(*ListStationsResponse)(nil),  // 7: protocol.ListStationsResponse
	(*DisconnectRequest)(nil),     // 8: protocol.DisconnectRequest
	(*DisconnectResponse)(nil),    // 9: protocol.DisconnectResponse
	(*ServerEvent)(nil),           // 10: protocol.ServerEvent
}
var file_pkg_protocol_protocol_proto_depIdxs = []int32{
	5,  // 0: protocol.ListStationsResponse.stations:type_name -> protocol.StationInfo
	3,  // 1: protocol.ServerEvent.announce:type_name -> protocol.AnnounceMessage
	4,  // 2: protocol.ServerEvent.invalid:type_name -> protocol.InvalidCommandMessage
	0,  // 3: protocol.SnowcastControl.Handshake:input_type -> protocol.HelloMessage
	6,  // 4: protocol.SnowcastControl.ListStations:input_type -> protocol.ListStationsRequest
	1,  // 5: protocol.SnowcastControl.SetStation:input_type -> protocol.SetStationMessage
	8,  // 6: protocol.SnowcastControl.Disconnect:input_type -> protocol.DisconnectRequest
	2,  // 7: protocol.SnowcastControl.Handshake:output_type -> protocol.WelcomeMessage
	7,  // 8: protocol.SnowcastControl.ListStations:output_type -> protocol.ListStationsResponse
	10, // 9: protocol.SnowcastControl.SetStation:output_type -> protocol.ServerEvent
	9,  // 10: protocol.SnowcastControl.Disconnect:output_type -> protocol.DisconnectResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_protocol_protocol_proto_init() }
func file_pkg_protocol_protocol_proto_init() {
	if File_pkg_protocol_protocol_proto != nil {
		return
	}
	file_pkg_protocol_protocol_proto_msgTypes[10].OneofWrappers = []any{
		(*ServerEvent_Announce)(nil),
		(*ServerEvent_Invalid)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_protocol_proto_rawDesc), len(file_pkg_protocol_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_protocol_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_protocol_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_protocol_proto_msgTypes,
	}.Build()
	File_pkg_protocol_protocol_proto = out.File
	file_pkg_protocol_protocol_proto_goTypes = nil
	file_pkg_protocol_protocol_proto_depIdxs = nil
}
