// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: pkg/protocol/protocol.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnowcastControl_Handshake_FullMethodName    = "/protocol.SnowcastControl/Handshake"
	SnowcastControl_ListStations_FullMethodName = "/protocol.SnowcastControl/ListStations"
	SnowcastControl_SetStation_FullMethodName   = "/protocol.SnowcastControl/SetStation"
	SnowcastControl_Disconnect_FullMethodName   = "/protocol.SnowcastControl/Disconnect"
)

// SnowcastControlClient is the client API for SnowcastControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnowcastControlClient interface {
	Handshake(ctx context.Context, in *HelloMessage, opts ...grpc.CallOption) (*WelcomeMessage, error)
	ListStations(ctx context.Context, in *ListStationsRequest, opts ...grpc.CallOption) (*ListStationsResponse, error)
	SetStation(ctx context.Context, in *SetStationMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerEvent], error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
}

type snowcastControlClient struct {
	cc grpc.ClientConnInterface
}

func NewSnowcastControlClient(cc grpc.ClientConnInterface) SnowcastControlClient {
	return &snowcastControlClient{cc}
}

func (c *snowcastControlClient) Handshake(ctx context.Context, in *HelloMessage, opts ...grpc.CallOption) (*WelcomeMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WelcomeMessage)
	err := c.cc.Invoke(ctx, SnowcastControl_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snowcastControlClient) ListStations(ctx context.Context, in *ListStationsRequest, opts ...grpc.CallOption) (*ListStationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStationsResponse)
	err := c.cc.Invoke(ctx, SnowcastControl_ListStations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snowcastControlClient) SetStation(ctx context.Context, in *SetStationMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SnowcastControl_ServiceDesc.Streams[0], SnowcastControl_SetStation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SetStationMessage, ServerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnowcastControl_SetStationClient = grpc.ServerStreamingClient[ServerEvent]

func (c *snowcastControlClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, SnowcastControl_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnowcastControlServer is the server API for SnowcastControl service.
// All implementations must embed UnimplementedSnowcastControlServer
// for forward compatibility.
type SnowcastControlServer interface {
	Handshake(context.Context, *HelloMessage) (*WelcomeMessage, error)
	ListStations(context.Context, *ListStationsRequest) (*ListStationsResponse, error)
	SetStation(*SetStationMessage, grpc.ServerStreamingServer[ServerEvent]) error
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	mustEmbedUnimplementedSnowcastControlServer()
}

// UnimplementedSnowcastControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnowcastControlServer struct{}

func (UnimplementedSnowcastControlServer) Handshake(context.Context, *HelloMessage) (*WelcomeMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedSnowcastControlServer) ListStations(context.Context, *ListStationsRequest) (*ListStationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStations not implemented")
}
func (UnimplementedSnowcastControlServer) SetStation(*SetStationMessage, grpc.ServerStreamingServer[ServerEvent]) error {
	return status.Error(codes.Unimplemented, "method SetStation not implemented")
}
func (UnimplementedSnowcastControlServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedSnowcastControlServer) mustEmbedUnimplementedSnowcastControlServer() {}
func (UnimplementedSnowcastControlServer) testEmbeddedByValue()                         {}

// UnsafeSnowcastControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnowcastControlServer will
// result in compilation errors.
type UnsafeSnowcastControlServer interface {
	mustEmbedUnimplementedSnowcastControlServer()
}

func RegisterSnowcastControlServer(s grpc.ServiceRegistrar, srv SnowcastControlServer) {
	// If the following call panics, it indicates UnimplementedSnowcastControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnowcastControl_ServiceDesc, srv)
}

func _SnowcastControl_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowcastControlServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnowcastControl_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowcastControlServer).Handshake(ctx, req.(*HelloMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnowcastControl_ListStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowcastControlServer).ListStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnowcastControl_ListStations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowcastControlServer).ListStations(ctx, req.(*ListStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnowcastControl_SetStation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SetStationMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SnowcastControlServer).SetStation(m, &grpc.GenericServerStream[SetStationMessage, ServerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnowcastControl_SetStationServer = grpc.ServerStreamingServer[ServerEvent]

func _SnowcastControl_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowcastControlServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnowcastControl_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowcastControlServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnowcastControl_ServiceDesc is the grpc.ServiceDesc for SnowcastControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnowcastControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.SnowcastControl",
	HandlerType: (*SnowcastControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _SnowcastControl_Handshake_Handler,
		},
		{
			MethodName: "ListStations",
			Handler:    _SnowcastControl_ListStations_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _SnowcastControl_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SetStation",
			Handler:       _SnowcastControl_SetStation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/protocol/protocol.proto",
}
